var data = [
    { 'testimonials': 'отзывы' },
    { 'appearance': 'внешний вид' },
    { 'dashboard': 'панель инструментов' },
    { 'collapse': 'свернуть' },
    { 'custom': 'настраиваемый' },
    { 'layout': 'макет' },
    { 'purpose': 'цель' },
    { 'additional': 'дополнительный' },
    { 'gutter': 'желоб, промежуток м-ду' },
    { 'brief': 'краткое' },
    { 'excerpt': 'отрывок, выписка, выдержка' },
    { 'founder': 'основатель, учредитель' },
    { 'sticky': 'липкий' },
    { 'instead': 'вместо' },
    { 'appreciation': 'признательность' },
    { 'enterprise': 'предприятие' },
    { 'advance': 'продвижение' },
    { 'values are deprecated': 'Значения устарели' },
    { 'revisions': 'изменения' },
    { 'slug': 'пуля, слизняк' },
    { 'collaborators': 'сотрудники' },
    { 'amount': 'количество' },
    { 'modern': 'современное' },
    { 'helpful': 'полезный' },
    { 'implementation': 'реализация' },
    { 'code snippet': 'фрагмент кода' },
    { 'neat': 'аккуратным' },
    { 'improve': 'улучшить' },
    { 'toggled dropdown': 'выпадающее меню' },
    { 'enqueued': 'в очереди' },
    { 'either side': 'любой стороне' },
    { 'manually': 'вручную' },
    { 'quotations': 'цитаты' },
    { 'adjustments': 'корректировка' },
    { 'what': 'что, какой' },
    { 'who': 'кто' },
    { 'where': 'где, куда' },
    { 'when': 'когда' },
    { 'why': 'почему, зачем' },
    { 'how': 'как' },
    { 'in 3 days': 'в течение 3 дней' },
    { 'in 2 weeks': 'через 2 недели' },
    { 'in 4 months': 'через 4 месяца' },
    { 'in 5 years': 'через 5 лет' },
    { 'in may': 'в мае' },
    { 'in winter': 'зимой' },
    { 'at 5': 'в 5' },
    { 'on monday': 'в понедельник' },
    { 'last - this - next (time/week)': 'последний, в этот, в следующий' },
    { 'fort of': 'типа того' },
    { 'i am a(one) developer': 'один из разработчиков' },
    { 'the(this)': 'этот' },
    { 'how much(little/time, money, love) ': 'нельзя посчитать' },
    { 'how many(few/days, hours, dollars, people)': 'можно посчитать' },
    { 'few': 'мало' },
    { 'some': 'несколько' },
    { 'everybody somebody nobody': 'о людях' },
    { 'everything something nothing': 'о вещах' },
    { 'everywhere somewhere nowhere': 'пространство' },
    { 'always sometimes never': 'время' },
    { 'when you go(without will)': 'когда ты пойдешь' },
    { 'if you go(without will)': 'если ты пойдешь' },
    { 'go dont go lets go': 'иди, не иди, пойдем' },
    { 'over': 'над' },
    { 'on': 'на' },
    { 'to': 'к' },
    { 'in': 'в' },
    { 'from': 'от' },
    { 'under': 'под' },
    { 'at': 'присутствие(не важно нахождение внутри)' },
    { 'between': 'между' },
    { 'with without': 'с без' },
    { 'for': 'для' },
    { 'about': 'около' },
    { 'myself': 'сам' },
    { 'yourself': 'себя' },
    { 'himself': 'сам' },
    { 'herself': 'сама' },
    { 'ourselves yourselves themselves': 'сами' },
    { 'yourselves': 'сами' },
    { 'themselves': 'сами' },
    { 'who is he': 'кто он(1)' },
    { 'who are they': 'кто они(много)' },
    { 'first second third fifth / -th': 'какой по счету' },
    { 'my birthday is on nineteenth of february nineteen eighty-eight': 'Когда твой день рождения' },
    { 'good morning': 'доброе утро(до 12)' },
    { 'good afternoon': 'добрый день(до 18)' },
    { 'good evening': 'добрый вечер' },
    { 'good night': 'доброй ночи' },
    { 'nice to meet you': 'приятно познакомиться' },
    { 'i regret': 'сожалею' },
    { 'lately': 'в последнее время' },
    { 'old older oldest': 'старший старше самый' },
    { 'beautiful more most': 'красивый более самый' },
    { 'most likely': 'скорее всего' },
    { 'better late than never': 'лучше поздно, чем никогда' },
    { 'based on': 'основан' },
    { 'to miss': 'промахнулся, пропустил' },
    { 'to release': 'выпустить' },
    { 'not so important': 'не так важно' },
    { 'most important': 'самое важное' },
    { 'invite': 'пригласить' },
    { 'to torture': 'пытать, мучать' },
    { 'refused': 'отказались' },
    { 'revenge': 'месть' },
    { 'far from you': 'далеко от тебя' },
    { 'devora': 'лишать жизни' },
    { 'devorce': 'развод' },
    { 'look': 'смотреть' },
    { 'to measure': 'измерять' },
    { 'whim': 'каприз' },
    { 'embarrassed': 'смущенн' },
    { 'contemporary': 'современный' },
    { 'grateful': 'благодарный' },
    { 'what is the difference between': 'в чем разница между' },
    { 'perceive': 'воспринимать' },
    { 'take part': 'принимать участие' },
    { 'learn from them': 'Учиться у них' },
    { 'ivent': 'событие' },
    { 'in good sense': 'В хорошем смысле' },
    { 'wise choice': 'мудрый выбор' },
    { 'quality': 'качество' },
    { 'support service': 'служба поддержка' },
    { 'this is why': 'вот почему' },
    { 'what cuisine': 'какая кухня' },
    { 'behind me': 'позади меня' },
    { 'stranger': 'незнакомец' },
    { 'foreigner': 'иностранец' },
    { 'foreign': 'иностранный' },
    { 'i want you to do something': 'Я хочу, чтобы ты кое-что сделал' },
    { 'i want you to be happy': 'Я хочу, чтобы ты был счастлив' },
    { 'lets discuss': 'давайте обсудим' },
    { 'one cant smoke here': 'здесь нельзя курить' },
    { 'if you do it': 'Если вы это сделаете' },
    { 'tastes': 'вкус' },
    { 'coach': 'тренер' },
    { 'to praise': 'хвалить' },
    { 'to scold': 'ругать' },
    { 'often': 'часто' },
    { 'consciousness': 'сознание' },
    { 'realize': 'понимать' },
    { 'avoid': 'избегать' },
    { 'Sit-ups': 'приседания' },
    { 'Push-ups': 'отжиманий' },
    { 'abs workout': 'качать пресс' },
    { 'impression': 'впечатление' },
    { 'breath': 'дыхание' },
    { 'beam, ray': 'луч' },
    { 'both': 'и то и другое' },
    { 'neither': 'ни то ни другое' },
    { 'rehearse': 'репетировать' },
    { 'calm': 'спокойствие' },
    { 'seldom': 'редко' },
    { 'woman(women)': 'женщина' },
    { 'man(men)': 'мужчина' },
    { 'people': 'люди' },
    { 'human': 'человек' },
    { 'mankind': 'человечество' },
    { 'society': 'общество  ' },
    // { '': '' },
    { 'blank': 'пустой' }
];