var data = [
  // {'' : ''},
  {'testimonials' : 'отзывы'},
  {'appearance' : 'внешний вид'},
  {'dashboard' : 'панель инструментов'},
  {'collapse' : 'свернуть'},
  {'custom' : 'настраиваемый'},
  {'layout' : 'макет'},
  {'purpose' : 'цель'},
  {'additional' : 'дополнительный'},
  {'gutter' : 'желоб, промежуток м-ду'},
  {'brief' : 'краткое'},
  {'excerpt' : 'отрывок, выписка, выдержка'},
  {'founder' : 'основатель, учредитель'},
  {'sticky' : 'липкий'},
  {'instead' : 'вместо'},
  {'appreciation' : 'признательность'},
  {'enterprise' : 'предприятие'},
  {'advance' : 'продвижение'},
  {'values are deprecated' : 'Значения устарели'},
  {'revisions' : 'изменения'},
  {'slug' : 'пуля, слизняк'},
  {'collaborators' : 'сотрудники'},
  {'amount' : 'количество'},
  {'modern' : 'современное'},
  {'helpful' : 'полезный'},
  {'implementation' : 'реализация'},
  {'code snippet' : 'фрагмент кода'},
  {'neat' : 'аккуратным'},
  {'improve' : 'улучшить'},
  {'toggled dropdown' : 'выпадающее меню'},
  {'enqueued' : 'в очереди'},
  {'either side' : 'любой стороне'},
  {'manually' : 'вручную'},
  {'quotations' : 'цитаты'},
  // {'' : ''},
  // {'' : ''},
  // {'' : ''},
];